<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Sales Force Leasing</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<META content="MSHTML 6.00.2719.2200" name=GENERATOR></HEAD>
<BODY vLink=#000066 aLink=#000066 link=#000066 bgColor=#ffffff leftMargin=0 
topMargin=0 
marginheight="0" marginwidth="0">
<SCRIPT language=JavaScript type=text/JavaScript>
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</SCRIPT>
<TABLE cellSpacing=0 cellPadding=0 width=768 border=0>
  <TBODY>
  <TR>
    <TD><IMG height=1 src="images/spacer.gif" width=86 border=0></TD>
    <TD><IMG height=1 src="images/spacer.gif" width=13 border=0></TD>
    <TD><IMG height=1 src="images/spacer.gif" width=636 
border=0></TD>
    <TD><IMG height=1 src="images/spacer.gif" width=11 border=0></TD>
    <TD><IMG height=1 src="images/spacer.gif" width=22 border=0></TD>
    <TD><IMG height=1 src="images/spacer.gif" width=1 
  border=0></TD></TR>
  <TR>
    <TD colSpan=5><IMG height=9 src="images/footer_p1_r1_c1.jpg" 
      width=768 border=0 name=footer_p1_r1_c1></TD>
    <TD><IMG height=9 src="images/spacer.gif" width=1 
  border=0></TD></TR>
  <TR>
    <TD rowSpan=4><IMG height=51 src="images/footer_p1_r2_c1.jpg" 
      width=86 border=0 name=footer_p1_r2_c1></TD>
    <TD colSpan=3>
      <DIV align=center><FONT face=Arial size=2>World Trade Center, Montecito # 38 piso 34, Desp. 23 y 24, Col. N&aacute;poles, C.P. 03810, M&eacute;xico, D.F.</FONT></DIV></TD>
    <TD rowSpan=4><IMG height=51 src="images/footer_p1_r2_c5.jpg" 
      width=22 border=0 name=footer_p1_r2_c5></TD>
    <TD><IMG height=20 src="images/spacer.gif" width=1 
  border=0></TD></TR>
  <TR>
    <TD colSpan=3><IMG height=4 src="images/footer_p1_r3_c2.jpg" 
      width=660 border=0 name=footer_p1_r3_c2></TD>
    <TD><IMG height=4 src="images/spacer.gif" width=1 
  border=0></TD></TR>
  <TR>
    <TD rowSpan=2><IMG height=27 src="images/footer_p1_r4_c2.jpg" 
      width=13 border=0 name=footer_p1_r4_c2></TD>
    <TD background=images/footer_p1_r4_c3.jpg>
      <DIV align=center><FONT face=Arial size=2>Tel.: (55) 5488 0774, Fax: ext. 105, 01 800 570 8588</FONT></DIV></TD>
    <TD rowSpan=2><IMG height=27 src="images/footer_p1_r4_c4.jpg" 
      width=11 border=0 name=footer_p1_r4_c4></TD>
    <TD><IMG height=20 src="images/spacer.gif" width=1 
  border=0></TD></TR>
  <TR>
    <TD><IMG height=7 src="images/footer_p1_r5_c3.jpg" width=636 
      border=0 name=footer_p1_r5_c3></TD>
    <TD><IMG height=7 src="images/spacer.gif" width=1 
  border=0></TD></TR></TBODY></TABLE>
</BODY></HTML>
