<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Sales Force Leasing</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<META content="MSHTML 6.00.2719.2200" name=GENERATOR></HEAD>
<BODY vLink=#000066 aLink=#000066 link=#000066 bgColor=#ffffff leftMargin=0 
topMargin=0 
marginheight="0" marginwidth="0">
<SCRIPT language=JavaScript type=text/JavaScript>
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</SCRIPT>
<table cellspacing=0 cellpadding=0 width=777 border=0>
  <tbody>
    <tr> 
      <td width="303"><img height=1 alt="" src="images/spacer.gif" width=295 
      border=0></td>
      <td width="158"><img height=1 alt="" src="images/spacer.gif" width=158 
      border=0></td>
      <td width="8"><img height=1 alt="" src="images/spacer.gif" width=8 
      border=0></td>
      <td width="152"><img height=1 alt="" src="images/spacer.gif" width=152 
      border=0></td>
      <td width="13"><img height=1 alt="" src="images/spacer.gif" width=13 
      border=0></td>
      <td width="142"><img height=1 alt="" src="images/spacer.gif" width=142 
      border=0></td>
      <td width="10"><img height=1 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td rowspan=6 background="images/headersales_r1_c1.gif"><table width="303" height="96" border="0" cellpadding="0" cellspacing="0">
          <tr> 
            <td width="67" align="center">
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="56" height="55">
                <param name="movie" value="images/esheader.swf">
                <param name="quality" value="high">
                <embed src="images/esheader.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="56" height="55"></embed></object></td>
            <td width="236">&nbsp;</td>
          </tr>
        </table></td>
      <td colspan=5><img height=42 alt="" 
      src="images/headersales_r1_c2.gif" width=465 border=0 
      name=headertd_r1_c2></td>
      <td><img height=42 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td colspan=2 rowspan=2><img height=31 alt="" 
      src="images/headersales_r2_c2.gif" width=159 border=0 
      name=headertd_r2_c2></td>
      <td background=images/headersales_r2_c4.gif> <div align=center><b><font face="Verdana, Arial, Helvetica, sans-serif" 
      color=#000066 size=2><a 
      href="bolsa.asp">Bolsa de trabajo</a></font></b></div></td>
      <td rowspan=5><img height=54 alt="" 
      src="images/headersales_r2_c5.gif" width=12 border=0 
      name=headertd_r2_c5></td>
      <td background=images/headersales_r2_c6.gif> <div align=center><b><font face="Verdana, Arial, Helvetica, sans-serif" 
      color=#000066 size=2><a 
      href="contacto.asp">Contáctenos</a></font></b></div></td>
      <td><img height=20 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td><img height=11 alt="" src="images/headersales_r3_c4.gif" 
      width=152 border=0 name=headertd_r3_c4></td>
      <td rowspan=2><img height=12 alt="" 
      src="images/headersales_r3_c6.gif" width=142 border=0 
      name=headertd_r3_c6></td>
      <td><img height=11 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td rowspan=2> <div align=center><font face="Verdana, Arial, Helvetica, sans-serif" 
      color=#000066 size=2><strong><a 
      href="somos.asp">Quienes somos</a></strong></font></div></td>
      <td rowspan=3><img height=23 alt="" 
      src="images/headersales_r4_c3.gif" width=8 border=0 
      name=headertd_r4_c3></td>
      <td background=images/headersales_r4_c4.gif rowspan=2> 
        <div align=center><font face="Verdana, Arial, Helvetica, sans-serif" 
      color=#000066 size=2><b><a 
      href="servicios.asp">Nuestros servicios</a></b></font></div></td>
      <td><img height=1 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td background=images/headersales_r5_c6.gif> 
        <div align=center><font face="Verdana, Arial, Helvetica, sans-serif" 
      color=#000066 size=2><b><a 
      href="factores.asp">Factores</a></b></font></div></td>
      <td><img height=19 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td><img height=3 alt="" src="images/headersales_r6_c2.gif" 
      width=158 border=0 name=headertd_r6_c2></td>
      <td><img height=3 alt="" src="images/headersales_r6_c4.gif" 
      width=152 border=0 name=headertd_r6_c4></td>
      <td><img height=3 alt="" src="images/headersales_r6_c6.gif" 
      width=142 border=0 name=headertd_r6_c6></td>
      <td><img height=3 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
    <tr> 
      <td bgcolor=#333399 colspan=6> <div align=right><font face="Verdana, Arial, Helvetica, sans-serif" 
      color=#ffffff size=1><b> 
          <script language=JavaScript>
<!-- damn --

function y2k(number) { return (number < 1000) ? number + 1900 : number; }


var now = new Date();
var textout;
var month = now.getMonth();
var date = now.getDate();
var year = now.getYear();
if (month==0) textout="Enero";
if (month==1) textout="Febrero";
if (month==2) textout="Marzo";
if (month==3) textout="Abril";
if (month==4) textout="Mayo";
if (month==5) textout="Junio";
if (month==6) textout="Julio";
if (month==7) textout="Agosto";
if (month==8) textout="Septiembre";
if (month==9) textout="Octubre";
if (month==10) textout="Noviembre";
if (month==11) textout="Deciembre";
textout += " " + date + ", " + y2k(year)+".";
document.write ( textout );

// -- end hiding -->
    
        </script>
          </b></font></div></td>
      <td><img height=4 alt="" src="images/spacer.gif" width=1 
      border=0></td>
    </tr>
  </tbody>
</table>
</BODY></HTML>
